let numbers = [
    "cero",
    "uno",
    "dos",
    "tres",
    "cuatro",
    "cinco",
    "seis",
    "siete",
    "ocho",
    "nueve",
    "diez",
    "once",
    "doce",
    "trece",
    "catorce",
    "quince",
    "dieciséis",
    "diecisiete",
    "dieciocho",
    "diecinueve",
    "veinte",
    "veintiuno",
    "veintidós",
    "veintitrés",
    "veinticuatro",
    "veinticinco",
    "veintiséis",
    "veintisiete",
    "veintiocho",
    "veintinueve",
    "treinta",
    "treinta y uno",
    "treinta y dós",
    "treinta y trés",
    "treinta y cuatro",
    "treinta y cinco",
    "treinta y séis",
    "treinta y siete",
    "treinta y ocho",
    "treinta y nueve",
    "cuarenta",
    "cuarenta y uno",
    "cuarenta y dós",
    "cuarenta y trés",
    "cuarenta y cuatro",
    "cuarenta y cinco",
    "cuarenta y séis",
    "cuarenta y siete",
    "cuarenta y ocho",
    "cuarenta y nueve",
    "cincuenta",
    "cincuenta y uno",
    "cincuenta y dós",
    "cincuenta y trés",
    "cincuenta y cuatro",
    "cincuenta y cinco",
    "cincuenta y séis",
    "cincuenta y siete",
    "cincuenta y ocho",
    "cincuenta y nueve",
    "sesenta",
]

export function numberToSpanishString(num) {
    if (numbers.length > num) {
        return numbers[num];
    } else {
        return "[" + num + "]";
    }
}